server:
  port: 8888

spring:
  h2:
    console:
      path: /h2-console
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
  application:
    name: authentication-service
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create

spring.se  security:


jwt:
  secret: mySecret
  expiration: 604800

